AdguardTeam/AdGuardHome

- issue_template.md
Leaving off the final |s makes it more likely y'all'll _see_ the data we input.
> Too many |s make table values disappear

- Dockerfile.arm
- Dockerfile.linux
- Dockerfile.linux64
Added Dockerfiles for Linux (386, amd64, and arm)
Tested working on RPi3+ as well.
```
docker run -d \
-p 53:53 \
-p 53:53/udp \
-p 80:3000 \
-v adguard_data:/data/adguard \
--restart always \
--name adguard-home \
ewrogers/adguard-home-arm:latest
```
Able to visit http://adguard-home in my browser and DNS queries are handled. Settings also persist across container restarts.
> Add Dockerfiles

- app.go
- control.go
- coredns_plugin/querylog.go
- dnsfilter/dnsfilter.go
- `json` is a package name so using `json` as a variable name is bad practice. 
- The return statement outside the `for` loop in `promptAndGet` is unreachable. 
- `go vet` reports: `control.go:225: github.com/miekg/dns.Question composite literal uses unkeyed fields`
> Minor tweaks

- README.md
On Linux you can run it listening on port 53 without root privs.  This is the best option: clients still send on port 53 (no wonky configs) and AdGuard doesn't run as root (!).
> Update README with instructions for setcap non-root use

- Dockerfile
- Dockerfile.travis
- docker-compose.yml
Containers security best practices say we should not run anything as root. In fact, this is actually enforced in some OpenStack distributions.
This patch makes AdguardHome run as `nobody`.
A drawback is that volume writing will happen as non-root (obviously), and thus file permissions will show their ugly head in the face of the user when she tries to mount a local directory in the container.  
Since the target user is advanced enough to use Docker, I think this is a reasonable tradeoff.
> Run as non-root user

- control.go
Corrects typo in parental control API error message.
When the sensitivity parameter was not passed to the parental control enable control call, it would error about the URL parameter missing.
> :ambulance: Corrects typo in parental control API error message

- home/blocked_services.go
Snapchat still works on Android if `impala-media-production.s3.amazonaws.com` isnt blocked
> Update blocked_services.go Snapchat Rules

- snapcraft.yaml
The current syntax means it will build on one of the architectures to run on all. That would be useful if it was an arch-independent snap, such as a shell script. But this contains arch-specific binaries. Using the syntax here, will get four separate builds (one per arch) which is the desired outcome. More information in the docs at https://snapcraft.io/docs/architectures
> Correct architecture builds

- dnsfilter/blocked_services.go
Discord now also uses discord.com as domain, this adds it to the blocked services list
> Update discord block for new domain

- home/auth.go
> home/auth: disable non-crypto RNG gosec lint check for session salt

- home/home.go
- home/options.go
- home/options_test.go
- home/service.go
I found that when running AGH with `-s run`, no other command line options were respected. This behavior made it difficult to specify custom working directory, configuration file, pid file, update check disablement, or GL-Inet emulation mode (whatever that is) when running AGH as a service.
This PR is organized into 3 commits:
1. Factor the CLI argument parsing out of `home/home.go` into `home/options.go` and make it generally side-effect free; add some tests
2. Provide a pseudo-inverse serialization operation from an options struct back to CLI arguments (roundtrip is idempotent and canonicalizing)
3. Integrate serialization into the service system so that `-s install` will create a service using whatever other CLI arguments are passed to it and `-s run` will actually use other passed CLI …
> Support  system service options

- dnsfilter/blocked_services.go
I used this domain list as a starting point for a NetFlix ipset whitelist and found that nflxso.net was a critical domain needed to use the NetFlix UI (GUI elements and cover art static content).
This blocked services system is currently explicitly for blacklisting but it stands to reason that these domain sets could be used for whitelisting as well. Where do you see this functionality going? I have found that YouTube requires a couple of extra domains that aren't exclusively used by YouTube so this directory schema may need some updating if it becomes whitelistable as well.
Thanks!
> dnsfilter/blocked_services: update netflix with nflxso.net SLD

- Dockerfile
No need to install tzdata as we already use the zoneinfo from Go. And to also avoid issues like golang/go#42216.
> Use zoneinfo from Go

- .github/workflows/build.yml
Use official Docker actions.
@ameshkov As a side note what about not using an action to push the image to the registry when a Git tag is pushed? Same for the app workflow would be nice too?
> Update docker workflow

- openapi/openapi.yaml
I went to create a client with the swagger codegen client (never tried it before) and after digging around in the generated code it looked like the auth settings were missing. After referencing [this](https://swagger.io/docs/specification/authentication/basic-authentication/) I got the codegen client working after adding those elements to the spec.
> Add security to openapi spec

- client/src/helpers/validators.js
`value` is always evaluated to true, due to the
check on the previous line
> Remove a superfluous condition

- client/src/helpers/helpers.js
- client/src/helpers/validators.js
- Using '' as default value is confusing when the function expects a number
as parameter
- `validateRequiredValue` can take a number as well as a string as first
parameter
> Fix some typing problems

- client/src/login/Login/Form.js
The username is case sensitive. Since most usernames are not capitalized, it is annoying that mobile browsers automatically capitalize the first letter in the login username input field. This pull request adds the autocapitalize="none" property which disables such behavior.
> Disabled autocapitalize on username field in mobile browsers

- .twosky.json
In line with how the other languages have their local names.
> Renamed Dutch to Nederlands in language selector

- internal/home/clients.go
This PR aims to prevent occasional reordering diffs like the following from appearing in the `AdGuardHome.yaml` config file:
```
clients:
-- name: device 1
-  ids:
-  - x.x.x.x
-  ...
- name: device 2
ids:
- y.y.y.y
...
+- name: device 1
+  ids:
+  - x.x.x.x
+  ...
```
This is problematic when including the config file in version control, since occasional no-op changes pop up and require reverting/committing.
I think the root cause of these reorders is that Go doesn't guarantee a consistent iteration order over maps (see the "Iteration order" section of https://go.dev/blog/maps), so e.g. different executions of an adguard docker container/daemon will produce different orders. By sorting the list of objects we create from the map before outputting them, we guarantee clients will be ordered …
> Prevent spurious diffs in config file by sorting Client objects before writing

- internal/home/auth.go
AdGuard Home currently logs failed login attempts but not successful ones. This PR adds logging for successful login attempts too in the same format as failed login attempts (Username, IP).
> Log successful login attempts in addition to failed ones

- client/public/index.html
- client/public/install.html
- client/public/login.html
This way, headers are no longer black, but the browser automatically fetches the appropriate color
**Current**:
**New**:
This also lets CSS themes be compatible:
> Remove `theme-color` from static HTML pages

- internal/filtering/blocked.go
The source rule uses regex that Golang doesn't support and is now changed to a normal rule.
> Fix unsupported regex for QQ blocked rules

- internal/home/controlfiltering.go
- openapi/openapi.yaml
This PR fixes some issues in the openapi scheme.
- RemoveUrlRequest is missing property 'whitelist'
- FilterStatus is missing property 'whitelist_filters'
- FilterSetUrl property 'data' is set to type Filter instead of inline object
- 'last_updated' of Filter is not required. At least it comes back as an empty string from the API
It also sets the filter 'last_updated' property to omitempty, to make sure the Filter json and scheme are valid.
> correct openapi schema

- README.md
* Add Asuswrt-Merlin-AdGuardHome-Installer (a.k.a. the installer that made adguardhome available to Asuswrt-Merlin Asus Routers)
> Update list of projects in README.md

- CHANGELOG.md
- internal/dnsforward/config.go
- internal/dnsforward/dnsforward.go
just like the upstream_dns_file
> feat: add dns.ipset_file setting

- CHANGELOG.md
- internal/home/control.go
Fix https://github.com/AdguardTeam/AdGuardHome/issues/4986
Even though the udp listener was listening on :443, the traffic was not sent to it, reason being the browser does not know that the website supports `h3`. 
reference : [link](https://www.smashingmagazine.com/2021/09/http3-practical-deployment-options-part3/#alt-svc)
So adding [Alt-Svc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) in the header, let the browser know that http3 is enabled
After adding the header 
`h3` is used
> Fix #4986 Web UI HTTP/3 not working

- CHANGELOG.md
- internal/aghtls/aghtls.go
- internal/dnsforward/config.go
- internal/home/home.go
- internal/home/web.go
Issue https://github.com/AdguardTeam/AdGuardHome/issues/4925
The Cipher `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` needs to be supported in order to pass `Forward Secrecy` test of [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html)
SSL Lab result after supporting this Cipher
Ref : https://www.namecheap.com/support/knowledgebase/article.aspx/9653/38/how-to-check-whether-the-server-supports-forward-secrecy/
This Cipher is allowed in [d.adguard-dns.com](d.adguard-dns.com) as well, 
SSL Labs report : [link](https://www.ssllabs.com/ssltest/analyze.html?d=d.adguard%2ddns.com&s=94.140.14.49&latest)
> Fix #4925: Allow users to choose TLS ciphers

- client/src/components/Dashboard/Counters.js
String "number_of_dns_query_days": "The number of DNS queries processed for the last {{count}} day",
Mistakenly displayed in milliseconds。
> fix error days

- README.md
Just a small clarification, because pi-hole can block adult domains with external block lists.
> Clarify the README comparison with pi-hole.

- go.mod
- go.sum
[v0.5.0 only supports Go 1.21+][1], and no dependencies require v0.5.0. This fixes building with Go 1.21.
[1]: https://github.com/mdlayher/socket/blob/18f45b55db258c8db998cab787ca7a11529105b6/CHANGELOG.md#v050
Closes #6446.
> all: downgrade github.com/mdlayher/socket

- openapi/openapi.yaml
The openapi schema has a wrong data type for the Client field upstreams_cache_size.
Currently in the schema it is defined as boolean, but in the struct an integer.
> correct schema type for client upstreams_cache_size

- README.md
Closes https://github.com/AdguardTeam/AdGuardHome/issues/6671
Adds the https://github.com/satheshshiva/Adguard-Home-Browser-Ext under the list of [Projects that use AdGuard Home](https://github.com/satheshshiva/AdGuardHome#uses) title
> Readme: Add browser extension project

- README.md
Mention 'AdGuardHome sync' in Applications that use AdGuardHome.
> Mention AdGuardHome sync in usages

- client/src/components/Settings/LogsConfig/index.js
**Step to reproduce bug:**
1. Open dashboard
2. Open client setting
3. Open settings
**Actual:**
Blank page by queryLogs.ignored undefined error
**Expect:**
Settings page display normally
It may a fix for #6634
> Fix blank settings page when access clients first

- internal/filtering/safesearch/rules/bing.txt
Edge sidebar uses a different search endpoint, as per https://support.microsoft.com/en-us/topic/blocking-adult-content-with-safesearch-or-blocking-chat-946059ed-992b-46a0-944a-28e8fb8f1814
> fix: enforce Bing safe search from Edge sidebar

- internal/filtering/safesearch/rules/google.txt
Add 3 new domains that appear in https://www.google.com/supported_domains but not in this list.  
For the technically minded, generate your own list with: `curl -fsSL https://www.google.com/supported_domains | sort | sed -E 's%^(.*)$%|www\1^$dnsrewrite=NOERROR;CNAME;forcesafesearch.google.com%'` :-)
> chore: update Google DNS list

- README.md
Closes #7477 by replacing the outdated link with the correct, updated link.
When I clicked the link aliased as wiki-start, the article had a banner at the top redirecting readers to a newer version on the wiki. This commit replaces the link to the outdated version with the link it redirects to, to save future visitors a click.
> Update wiki-start in README.md

- client/src/components/Dashboard/index.tsx
Closes #7599
This change should in theory fix the incorrect time placement like described in the linked issue.
**WARNING:** I wasn't able to run `make js-lint` etc. because I am missing the required tools... Someone needs to check this for me.
> Fix time placement in `enable_protection_timer` text

- client/src/components/Settings/Clients/AutoClients.tsx
- client/src/components/Settings/Clients/ClientsTable/ClientsTable.tsx
This PR updates the content displayed in AutoClient.tsx and ClientsTable.tsx  to use a formatted number.
1. Applied formatNumber to clientStats before rendering it as content in <LogsSearchLink>.
2.Applied formatNumber to numeric values in the Cell method to ensure consistent formatting.
Since I noticed that this PR https://github.com/AdguardTeam/AdGuardHome/pull/7505 introduces a function for formatting numeric display and applies it only to the homepage, I’ve extended its usage to also format numbers in the Setting Clients section to improve readability.
Thank you.
> Format values in Setting clients
