AdguardTeam/AdGuardHome

Filters/filter.template, Filters/filter.txt
1st noted in https://github.com/AdguardTeam/AdguardForAndroid/issues/13#issuecomment-328372370 🤷‍♂️
=> Fix minor typo

Filters/filter.template
https://github.com/AdguardTeam/AdguardDNS/issues/220
=> Added list of the crypto-miners

Filters/parser.py
https://github.com/AdguardTeam/AdguardDNS/issues/215
=> Added support parsing `##` symbols

Filters/exceptions.txt
ads replacement https://forum.adguard.com/index.php?threads/23410/page-7#post-165504
=> 9to5mac.com - ads replacement

Filters/exclusions.txt
=> Fix: olymptrade.com

Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardDNS/issues/298
=> Fixing Nvidia Shield Tv issue

Filters/exceptions.txt, Filters/exclusions.txt
https://github.com/AdguardTeam/AdguardFilters/issues/19113
=> Fixing TD Bank iOS app

README.md
Correction of the incorrect DNSCrypt URL in the README.md (as on https://github.com/jedisct1/dnscrypt-proxy).
=> Updating the DNSCrypt URL

client/src/components/Filters/index.js, client/src/helpers/trackers/trackers.js
=> Formatted 'Rules count' number with thousands separator

config.go, dns.go
Another pull request for #550 hopefully without all the other changes this time
=> Config dns address

dnsfilter/safesearch.go
[duckduckgo.com](https://duckduckgo.com) also has [a Safe Mode](https://duck.co/help/features/safe-search), this patch adds support in AdGuard Home for that.
=> Patch: Add Duckduckgo SafeSearch

client/src/components/ui/Footer.js
Fixes: https://github.com/AdguardTeam/AdGuardHome/issues/1027
=> Footer: Open adguard.com in new tab

client/src/components/Settings/Encryption/Form.js
=> Bind encryption source disabled state to form

client/src/components/Settings/Dns/Upstream/Examples.js
Update rest of examples to AG DNS not only quic protocol address
=> Update DNS examples

README.md
=> Fix link address

client/src/components/Dashboard/index.js
This increases a bit the accessibility.
=> Add a title to the refresh buttons

README.md
Change lighthttpd to lighttpd
https://www.lighttpd.net
=> Fix spelling of lighttpd

internal/filtering/blocked.go
Pretty much what the title says.
=> Found a few more domains for Disney+ and Facebook

scripts/make/Dockerfile
Remove additional `--update` and manual clean up for `apk` in Dockerfile, this will make the Dockerfile tidier!
=> Simplify Dockerfile Alpine Linux apk usage

README.md
It'll make it just a little bit easier to read it
=> Enable code block syntax hightlight in README.md

internal/dnsforward/config.go
Hi there!
First, I'd like to thank the team for the amazing software! 🎉
I've been using AdGuardHome for over a year and it has never failed me 😃
This pull request addresses an issue I've noticed that happens whenever the first upstream resolver is down (admittedly I think it might only happen when using DNSCrypt): The blocklists won't update.
Normally, the old blocklists would be used again in such a case, but if there are no old lists then nothing is used.
Why isn't the next resolver retrieved? Well, I'm not sure, it does seem to happen with plain DNS resolvers, but it appears it doesn't with DNSCrypt (haven't tried other protocols though).
Maybe this 5 min delay to wait for the resolver's response is guilty (plain DNS don't wait 5 min, but DNSCrypt apparently does): …
=> Honor the user-defined UpstreamMode for the internal DNS proxy

internal/filtering/blocked.go
Add cloudflareaccess.com for Cloudflare Service
- Use for Cloudflare Zero Trust
=> Update Cloudflare Service

internal/filtering/blocked.go
Add DisneyNow, Star+ and Disney+ Hotstar
=> Add more Disney service

internal/home/web.go
Issue: https://github.com/AdguardTeam/AdGuardHome/issues/4930
=> add support for plain h2c

go.mod, internal/dhcpd/conn_unix.go, internal/dhcpd/conn_unix_test.go, internal/dhcpd/v4_unix.go, internal/dhcpd/v4_unix_test.go
If this is really all that's needed to remove this dep I will make a similar pull for https://github.com/insomniacslk/dhcp to remove this dep there.
=> Remove direct dep on mdlayher/raw package

internal/dnsforward/stats.go, internal/home/service.go
=> chore: fix function names in comment

client/src/components/Dashboard/Counters.tsx, client/src/helpers/helpers.tsx
I have stumbled upon incorrect formatting in General Statistics myself, found the issue #7329 and decided to fix it. I verified that the frontend builds, that it runs, and that the issue is fixed with this PR.
=> Format values in General Statistics (fixes #7329)
